services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_internal_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_internal_net

  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api_service
    restart: unless-stopped
    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - QDRANT_BASE_URL=${QDRANT_BASE_URL}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - QDRANT_VECTOR_SIZE=${QDRANT_VECTOR_SIZE}
      - HF_DATASET_NAME=${HF_DATASET_NAME}
      - HF_DATASET_SUBSET=${HF_DATASET_SUBSET}

    depends_on:
      - ollama
      - qdrant
    networks:
      - rag_internal_net

networks:
  rag_internal_net:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  qdrant_data:
    driver: local