from pydantic import BaseModel, Field
from typing import List
from .fields import RetrievalStatus, PipelineStatus


class RAGIngestResponse(BaseModel):
    """Response model containing aggregated statistics produced by the ingestion pipeline."""

    status: PipelineStatus
    documents: int
    chunks: int
    embeddings: int


class RAGQueryRequest(BaseModel):
    """Request model for executing a full RAG query over the indexed document collection."""

    query: str = Field(..., description="User query to be processed by the RAG pipeline")
    limit: int = Field(5, description="Maximum number of retrieved documents")


class RetrievedDocument(BaseModel):
    """
    Metadata representation of a retrieved document, including identifier, score, and content.
    """

    id: str = Field(..., description="Unique identifier of the retrieved document")
    score: float = Field(..., description="Similarity score assigned by the retriever")
    text: str = Field(..., description="Content of the retrieved document")


class RAGQueryResponse(BaseModel):
    """
    Response model containing the generated answer, supporting context, and retrieval metadata.
    """

    status: PipelineStatus = Field(..., description="Execution status of the RAG pipeline")
    answer: str = Field(..., description="Final answer generated by the RAG pipeline")
    context: List[str] = Field(..., description="List of context passages used for generation")
    retrieved: List[RetrievedDocument] = Field(..., description="Retrieved documents metadata")


class RAGRetrieveRequest(BaseModel):
    """
    Request model for retrieving semantically relevant documents from the vector store.
    """

    query: str = Field(..., description="User query for document retrieval")
    limit: int = Field(5, description="Maximum number of retrieved documents")


class RAGRetrieveResponse(BaseModel):
    """
    Response model containing the results of the retrieval operation.
    """

    status: RetrievalStatus = Field(..., description="Status of the retrieval operation")
    retrieved: List[RetrievedDocument] = Field(..., description="List of retrieved documents")


class RAGEmbedRequest(BaseModel):
    """
    Request model for generating an embedding vector from a text input.
    """

    text: str = Field(..., description="Text to be converted into an embedding vector")


class RAGEmbedResponse(BaseModel):
    """
    Response model containing the embedding vector produced by the embedding model.
    """

    embedding: List[float] = Field(..., description="Generated embedding vector")